FROM  nginx
#  image will be pulled  from Docker HUB 
MAINTAINER  ashutoshh@linux.com
WORKDIR  /usr/share/nginx/html 
#  use of workdir it change  directory during  image  build time 
# very similar to cd  command in linux 
COPY  webapp  .
#  Note  if  we don't define parent process 
#  it is going to take parent process of FROM image 
