FROM  centos
MAINTAINER  ashutoshh@linux.com
ARG  x=ftp
ENV  z=$x
#  arg  will provide you option to change parameter without chaning  dockerfile 
# you can use numerb of times  arg  instruction 
# arg  variable will not be present in newly created docker image 
RUN yum  install  $z  -y
