apiVersion: v1
kind: Pod
metadata:
  namespace: anil
  creationTimestamp: null
  labels:
    run: anilpod
  name: anilpod
spec:
  containers:
  - image: dockerashu/ciscoashu:june292020
    name: anilpod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
