apiVersion: v1
kind: ReplicationController
metadata:
 name: anilc1
 namespace: anil
spec: 
 replicas: 2
 template:
  metadata:
  namespace: anil
  creationTimestamp: null
  labels:
    run: anilpod
  name: anilpod
spec:
  containers:
  - image: dockerashu/ciscoashu:june292020
    name: anilpod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
