apiVersion: v1
kind: ReplicationController
metadata:
 name: anilc1 # name of rc
 namespace: anil # name of namespace
spec:
 replicas: 2 # for single application there will 2 pods deployed
 template: # info about pod
  metadata:
   name: anilpod1 # name of pod optional field here
   labels:
    x: helloashu
  spec:
   containers:
   - name: anilc1
     image: dockerashu/ciscoashu:june292020
     ports:
     - containerPort: 80
