apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: podx1
  name: podx1
spec:
  containers:
  - image: alpine
    name: podx1
    command: ["/bin/sh","-c","ping 8.8.8.8"]  #  command is replacement of entrypoint based parent process in docker image
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
