apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:   #  this is  for  defining  labels to  pod 
   run: ashuwebpod1    #  key: value format of label 
  name: ashuwebpod222  # name of the pod 
spec:
  containers:  #  info about  containers 
  - image: dockerashu/ciscoashu:june292020 # docker  image  name 
    name: ashuwebpod1  #  name of container 
    ports:   #  optional field  but its a best practise 
    - containerPort: 80  #  this must be same as Dockerfile  expose keyword 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
