apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ashupod5
  name: ashupod5
  namespace: ashu   #  my namespace  namespce  must be existing  it is not going  to create 
spec:
  volumes:   #  can crete no of volumes
  - name: ashuvol1   #  first volume 
    hostPath:   #  Host location 
     path: /mnt  #  this location will be used stored data by pod on the worker node 
     type: Directory 
  containers:
  - image: alpine
    name: ashupod5
    volumeMounts:
    - name: ashuvol1  # name of volume 
      mountPath:  /mnt/ciscodata   #  this location will be created when pod will created inside container
    command: ["/bin/sh","-c","while true; do  date  >>/mnt/ciscodata/time.txt;sleep 10;done"]   
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
